# Sticker's paths for each category
STICKER_PATHS = {'hats': ['./stickers/hats/None.png', './stickers/hats/santa-hat.png', './stickers/hats/top-hat.png', './stickers/hats/party-hat.png', './stickers/hats/witch-hat.png', './stickers/hats/green-hat.png', './stickers/hats/chef-hat.png', './stickers/hats/Christmas-hat.png', './stickers/hats/mexican-hat.png'], 
                'animal face': ['./stickers/animal face/None.png', './stickers/animal face/dog.png', './stickers/animal face/rabbit.png', './stickers/animal face/unicorn.png', './stickers/animal face/deer.png', './stickers/animal face/cat.png', './stickers/animal face/fox.png', './stickers/animal face/pig.png', './stickers/animal face/bear.png'], 
                'ears': ['./stickers/ears/None.png', './stickers/ears/pink-bunny-ears.png', './stickers/ears/fox-ears.png', './stickers/ears/fluffy-bunny-ear.png', './stickers/ears/fluffy-pink-bunny.png', './stickers/ears/tiger-ear.png', './stickers/ears/white-bunny-ears.png', './stickers/ears/bent-rabbit-ears.png', './stickers/ears/pink-bunny-ears-2.png'], 
                'glasses': ['./stickers/glasses/None.png', './stickers/glasses/heart-sunglasses.png', './stickers/glasses/round-eyeglasses.png', './stickers/glasses/pink-sunglasses.png', './stickers/glasses/cool-sunglasses.png', './stickers/glasses/gray-sunglasses.png', './stickers/glasses/blue-sunglasses.png', './stickers/glasses/rainbow-glasses.png', './stickers/glasses/reading-eyeglasses.png'], 
                'noses': ['./stickers/noses/None.png', './stickers/noses/dog-nose.png', './stickers/noses/pig-nose.png', './stickers/noses/clown-nose.png', './stickers/noses/dog-nose4.png', './stickers/noses/dog-nose5.png', './stickers/noses/dog-nose6.png', './stickers/noses/dog-nose2.png', './stickers/noses/dog-nose3.png'], 
                'headbands': ['./stickers/headbands/None.png', './stickers/headbands/deer-headband.png', './stickers/headbands/blue-headband.png', './stickers/headbands/bow-headband.png', './stickers/headbands/flower-headband.png', './stickers/headbands/devil-headband.png', './stickers/headbands/cat-headband.png', './stickers/headbands/christmas-headband.png', './stickers/headbands/green-headband.png']}




# Creating a new dictionary with sticker name as key and category as value
STICKER_TO_CATEGORY = {'santa-hat.png': 'hats',
'top-hat.png': 'hats',
'party-hat.png': 'hats',
# 'graduation-hat2.png': 'hats',
'mexican-hat.png': 'hats',
'witch-hat.png': 'hats',
'green-hat.png': 'hats',
'chef-hat.png': 'hats',
'Christmas-hat.png': 'hats',
# 'magic-hat.png': 'hats',
# 'cap.png': 'hats',
'dog.png': 'animal face',
'rabbit.png': 'animal face',
'unicorn.png': 'animal face',
'deer.png': 'animal face',
'cat.png': 'animal face',
'fox.png': 'animal face',
'pig.png': 'animal face',
'bear.png': 'animal face',
'pink-bunny-ears.png': 'ears',
'fox-ears.png': 'ears',
'fluffy-bunny-ear.png': 'ears',
'fluffy-pink-bunny.png': 'ears',
'tiger-ear.png': 'ears',
'white-bunny-ears.png': 'ears',
'bent-rabbit-ears.png': 'ears',
'pink-bunny-ears-2.png': 'ears',
'heart-sunglasses.png': 'glasses',
'round-eyeglasses.png': 'glasses',
'pink-sunglasses.png': 'glasses',
'cool-sunglasses.png': 'glasses',
'gray-sunglasses.png': 'glasses',
'blue-sunglasses.png': 'glasses',
'rainbow-glasses.png': 'glasses',
'reading-eyeglasses.png': 'glasses',
'dog-nose.png': 'noses',
'pig-nose.png': 'noses',
'clown-nose.png': 'noses',
'dog-nose4.png': 'noses',
'dog-nose5.png': 'noses',
'dog-nose6.png': 'noses',
'dog-nose2.png': 'noses',
'dog-nose3.png': 'noses',
# 'dear-ears.png': 'headbands',
# 'gray-bunny-ears.png': 'headbands',
# 'bunny-headband.png': 'headbands',
# 'kitten-ears.png': 'headbands',
'devil-headband.png': 'headbands',
'cat-headband.png': 'headbands',
'christmas-headband.png': 'headbands',
'blue-headband.png': 'headbands',
'bow-headband.png': 'headbands',
'deer-headband.png': 'headbands',
'flower-headband.png': 'headbands',
'green-headband.png': 'headbands',

# 'bear-headbands.png': 'headbands'
}
