# Sticker's paths for each category
STICKER_PATHS = {'hats': ['./stickers/hats/None.png', './stickers/hats/santa.png', './stickers/hats/top.png', './stickers/hats/party.png', './stickers/hats/witch.png', './stickers/hats/green.png', './stickers/hats/chef.png', './stickers/hats/Christmas.png', './stickers/hats/mexican.png'], 
                'animal face': ['./stickers/animal face/None.png', './stickers/animal face/dog.png', './stickers/animal face/rabbit.png', './stickers/animal face/unicorn.png', './stickers/animal face/deer.png', './stickers/animal face/cat.png', './stickers/animal face/fox.png', './stickers/animal face/pig.png', './stickers/animal face/bear.png'], 
                'ears': ['./stickers/ears/None.png', './stickers/ears/bunny.png', './stickers/ears/fox.png', './stickers/ears/fluffy.png', './stickers/ears/carrot.png', './stickers/ears/tiger.png', './stickers/ears/white.png', './stickers/ears/bent.png', './stickers/ears/bunny2.png'], 
                'glasses': ['./stickers/glasses/None.png', './stickers/glasses/heart.png', './stickers/glasses/round.png', './stickers/glasses/pink.png', './stickers/glasses/cool.png', './stickers/glasses/gray.png', './stickers/glasses/blue.png', './stickers/glasses/rainbow.png', './stickers/glasses/reading.png'], 
                'noses': ['./stickers/noses/None.png', './stickers/noses/clown.png', './stickers/noses/pig.png', './stickers/noses/dog1.png', './stickers/noses/dog2.png', './stickers/noses/dog3.png', './stickers/noses/dog4.png', './stickers/noses/dog5.png', './stickers/noses/dog6.png'], 
                'headbands': ['./stickers/headbands/None.png', './stickers/headbands/deer.png', './stickers/headbands/blue.png', './stickers/headbands/bow.png', './stickers/headbands/flower.png', './stickers/headbands/devil.png', './stickers/headbands/cat.png', './stickers/headbands/christmas.png', './stickers/headbands/green.png']}




# Creating a new dictionary with sticker name as key and category as value
STICKER_TO_CATEGORY = {'santa.png': 'hats',
'top.png': 'hats',
'party.png': 'hats',
# 'graduation-hat2.png': 'hats',
'mexican.png': 'hats',
'witch.png': 'hats',
'green.png': 'hats',
'chef.png': 'hats',
'Christmas.png': 'hats',
# 'magic-hat.png': 'hats',
# 'cap.png': 'hats',
'dog.png': 'animal face',
'rabbit.png': 'animal face',
'unicorn.png': 'animal face',
'deer.png': 'animal face',
'cat.png': 'animal face',
'fox.png': 'animal face',
'pig.png': 'animal face',
'bear.png': 'animal face',
'bunny.png': 'ears',
'fox.png': 'ears',
'fluffy.png': 'ears',
'carrot.png': 'ears',
'tiger.png': 'ears',
'white.png': 'ears',
'bent.png': 'ears',
'bunny2.png': 'ears',
'heart.png': 'glasses',
'round.png': 'glasses',
'pink.png': 'glasses',
'cool.png': 'glasses',
'gray.png': 'glasses',
'blue.png': 'glasses',
'rainbow.png': 'glasses',
'reading.png': 'glasses',
'dog1.png': 'noses',
'pig.png': 'noses',
'clown.png': 'noses',
'dog2.png': 'noses',
'dog3.png': 'noses',
'dog4.png': 'noses',
'dog5.png': 'noses',
'dog6.png': 'noses',
# 'dear-ears.png': 'headbands',
# 'gray-bunny-ears.png': 'headbands',
# 'bunny-headband.png': 'headbands',
# 'kitten-ears.png': 'headbands',
'devil.png': 'headbands',
'cat.png': 'headbands',
'christmas.png': 'headbands',
'blue.png': 'headbands',
'bow.png': 'headbands',
'deer.png': 'headbands',
'flower.png': 'headbands',
'green.png': 'headbands',

# 'bear-headbands.png': 'headbands'
}
